exports.ngsql:db_exec ( "CREATE TABLE IF NOT EXISTS log_punish ( _time VARCHAR(35), account VARCHAR(40), serial VARCHAR(50), admin VARCHAR(40), log TEXT )" )


local forwardLogsToConsole = false
local paths = { action = "logs/action", punish = "logs/punish", chat = "logs/chat", server="logs/server", sql="logs/sql" }
function outputActionLog ( log )
	local path = paths.action .. "/"..exports.NGPlayerFunctions:getToday ( )..".txt"
	if ( not fileExists ( path ) ) then
		local f = fileCreate ( path )
		fileWrite ( f, "This file was generated by Console at "..tostring ( getToday ( ) ).."\n\n\n" )
		fileFlush ( f )
		fileClose ( f )
	end
	local f = fileOpen ( path )
	fileSetPos ( f, fileGetSize ( f ) )

	local log = "["..getToday().."] "..tostring ( log )
	fileWrite ( f, "\n"..log )
	fileFlush ( f )
	fileClose ( f )

	if ( forwardLogsToConsole ) then print ( "[ACTION LOG] "..tostring( log ) ) end
end

function outputPunishLog ( player, admin, log )
	local account = getPlayerAccount ( player )
	if ( isGuestAccount ( account ) ) then
		account = "Guest"
	else
		account = getAccountName ( account )
	end

	local from = "Server"
	if ( type ( admin ) ~= "string" and isElement ( admin ) and getElementType ( admin ) == "player" ) then
		from = getPlayerName ( admin )
	end

	local serial = getPlayerSerial ( player )
	exports.ngsql:db_exec ( "INSERT INTO log_punish ( _time, account, serial, admin, log ) VALUES ( ?, ?, ?, ?, ? )", getToday(), account, serial, from, log )

end

function outputChatLog ( chat, log )
	local path = paths.chat .. "/"..exports.NGPlayerFunctions:getToday ( )..".txt"
	if ( not fileExists ( path ) ) then
		local f = fileCreate ( path )
		fileWrite ( f, "This file was generated by Console at "..tostring ( getToday ( ) ).."\n\n\n" )
		fileFlush ( f )
		fileClose ( f )
	end
	local f = fileOpen ( path )
	fileSetPos ( f, fileGetSize ( f ) )

	local log = "["..getToday().."]  ("..tostring ( chat )..") -> "..tostring ( log )
	fileWrite ( f, "\n"..log )
	fileFlush ( f )
	fileClose ( f )

	if ( forwardLogsToConsole ) then print ( "[CHAT LOG] "..tostring( log ) ) end
end

function outputServerLog ( log )
	local path = paths.server .. "/"..exports.NGPlayerFunctions:getToday ( )..".txt"
	if ( not fileExists ( path ) ) then
		local f = fileCreate ( path )
		fileWrite ( f, "This file was generated by Console at "..tostring ( getToday ( ) ).."\n\n\n" )
		fileFlush ( f )
		fileClose ( f )
	end
	local f = fileOpen ( path )
	fileSetPos ( f, fileGetSize ( f ) )
	local log = "["..getToday().."] "..tostring ( log )
	fileWrite ( f, "\n".. tostring ( log ) )
	fileFlush ( f )
	fileClose ( f )

	if ( forwardLogsToConsole ) then print ( "[SERVER LOG] "..tostring( log ) ) end
end

function outputSQLLog ( log )
	local path = paths.sql .. "/"..exports.NGPlayerFunctions:getToday ( )..".txt"
	if ( not fileExists ( path ) ) then
		local f = fileCreate ( path )
		fileWrite ( f, "This file was generated by Console at "..tostring ( getToday ( ) ).."\n\n\n" )
		fileFlush ( f )
		fileClose ( f )
	end
	local f = fileOpen ( path )
	fileSetPos ( f, fileGetSize ( f ) )

	local log = "["..getToday().."] "..tostring ( log )
	fileWrite ( f, "\n\n\n"..log )
	fileFlush ( f )
	fileClose ( f )

	if ( forwardLogsToConsole ) then print ( "[SQL LOG] "..tostring( log ) ) end
end

function getToday ( ) 
	local time = getRealTime ( )
	local year = time.year+1900
	local month = time.month+1
	local day = time.monthday
	local hour = time.hour
	local min = time.minute
	local sec = time.second
	if ( month < 10 ) then month = 0 .. month end
	if ( day < 10 ) then day = 0 .. day end
	if ( hour < 10 ) then hour = 0 .. hour end
	if ( min < 10 ) then min = 0 .. min end
	if ( sec < 10 ) then sec = 0 .. sec end
	return table.concat({year,month,day},":").."-"..table.concat({hour,min,sec},":")
end












-- Log some common actions --
setTimer ( function ( ) 
	addEventHandler ( "onResourceStart", root, function ( source )
		outputServerLog ( getResourceName ( source ).. " is starting up..." )
	end ) 
	
	addEventHandler ( "onResourceStop", root, function ( source )
		outputServerLog ( getResourceName ( source ).." is stopping..." )
	end ) 
	
	
	---------------------------------
	-- Prevent fake staff
	---------------------------------
	addEventHandler ( "onPlayerChangeNick", root, function ( o, n )
		if ( string.sub ( n, 0, 4 ):upper ( ) == "[NG]" and not exports.NGAdministration:isPlayerStaff ( source ) ) then
			exports.NGMessages:sendClientMessage ( "You cannot have the [NG] tag, as for you're not a staff member", source, 255, 0, 0 )
			cancelEvent ( )
			return
		end
		outputActionLog ( o.." has changed their nick to ".. n )
	end )
	
	addEventHandler ( "onPlayerLogin", root, function ( )
		if ( string.sub ( getPlayerName ( source ), 0, 4 ):upper() == "[NG]" and not exports.NGAdministration:isPlayerStaff ( source ) ) then
			local n = string.sub ( getPlayerName ( source ), 5, string.len ( getPlayerName ( source ) ) )
			setPlayerName ( source, n )
			exports.NGMessages:sendClientMessage ( "Your name has been changed to "..tostring(n).." because you had the [NG] tag and you're not staff", source, 255, 255, 0 )
		end
	end )
	
	for _, source in pairs ( getElementsByType ( "player" ) ) do
		local n = getPlayerName ( source )
		if ( string.sub ( n, 0, 4 ) == "[NG]" and not exports.NGAdministration:isPlayerStaff ( source ) ) then
			local n = string.sub ( getPlayerName ( source ), 5, string.len ( getPlayerName ( source ) ) )
			setPlayerName ( source, n )
			exports.NGMessages:sendClientMessage ( "Your name has been changed to "..tostring(n).." because you had the [NG] tag and you're not staff", source, 255, 255, 0 )
		end
	end
	
	
end, 2000, 1 )